target 'ios' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-11'    # Swift Concurrency implementation
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-11'  # Combine implementation
end